### ISSUE TITLE
Very important

### ISSUE THREAD

**Issue by alexmb15** [GuistF/Web#1]
Hello! Why are you blocking me everywhere? JUST LISTEN TO ME! I am not a scammer, and you will be convinced of this if you agree to talk to me. It is very important and profitably for you.

**Comment by alexmb15** [comment]
telegram @alexmb152
Just add and listen to me

**Comment by GuistF** [comment]
hi @alexmb15 could you kindly indicate to me that i can help. I am ready to listen to you through here.

**Comment by alexmb15** [comment]
I will help you earn 400 tokens worth over $ 1000 with one condition that you share 100 tokens with me. Do you agree?
If you agree, they will appear in your wallet 0xa6d91f3795f934bb5f703724337f39c0f1a95fd5
After you receive them, send 100 tokens to my address, which I will indicate

**Comment by GuistF** [comment]
hey, I don't work with investments.i really appreciate your attention to sharing. I'm just work with design stuff.
thanks!

**Comment by alexmb15** [comment]
you have 400 tokens in your wallet worth more than $ 1000. If you are an honest person send 100 tokens to wallet 0x591cD7d56A07AdCAD86d5E129ec2C71016B6DA02

**Comment by alexmb15** [comment]
the rest you can sell for binance

**Comment by alexmb15** [comment]
https://www.binance.com/ru/trade/UNI_USDT?layout=basic

**Comment by GuistF** [comment]
Sorry, I'm not interested.
You shouldn't have sent these tokens without my permission. 
https://etherscan.io/tx/0x13c55c20eaa44020eb83b42b780792127d8e9bce694210d7a4e60a2208254068
I will return in the total amount on the same wallet after document this situation.
